package constants

const ELASTIC_USER_ID_FIELD = "userId"
const ELASTIC_STARRED_FIELD = "starred"
const ELASTIC_VISIBLE_FIELD = "visible"
const ELASTIC_STARRED_BY_USER_FIELD = "starredByUser"
const ELASTIC_SUCCESS_PERCENTAGE_FIELD = "successPercentage"
const ELASTIC_TITLE_FIELD = "title"
const ELASTIC_CONTENT_FIELD = "content"
const ELASTIC_TAG_FIELD = "tags"
const ELASTIC_ID_FIELD = "id"
const ELASTIC_DISPLAY_NAME_FIELD = "display_name"
const ELASTIC_DOWNVOTED_BY_USER_FIELD = "downvotedByUser"
const ELASTIC_UPVOTED_BY_USER_FIELD = "upvotedByUser"
const ELASTIC_NUMBER_OF_FAILURES = "numberOfFailures"
const ELASTIC_NUMBER_OF_SUCCESSES = "numberOfSuccesses"
const ELASTIC_NUMBER_OF_TRIES = "numberOfTries"
const ELASTIC_UPDATED_AT_FIELD = "updatedAt"
const ELASTIC_USERNAME_FIELD = "username"
