package constants

const ELASTIC_SEARCH_PASSWORD = "ELASTIC_PASSWORD"
const ELASTIC_SEARCH_USERNAME = "ELASTIC_USERNAME"
const ELASTIC_SEARCH_CERT_PATH = "ELASTIC_CERT_PATH"
const ELASTIC_SEARCH_HOST = "ELASTIC_SEARCH_HOST"
const ELASTIC_PLAYBOOK_INDEX = "ELASTIC_PLAYBOOK_INDEX"

const PICKUP_LINE_INDEX_NAME = "PICKUP_LINE_INDEX_NAME"
const TAGS_INDEX_NAME = "TAGS_INDEX_NAME"
const USER_INDEX_NAME = "USER_INDEX_NAME"

const STORAGE_PATH = "STORAGE_PATH"

const DATABASE_DSN = "DATABASE_DSN"
const JWT_SECRET_KEY = "JWT_SECRET_KEY"
