// Code generated by MockGen. DO NOT EDIT.
// Source: mappers/DtoMapper.go
//
// Generated by this command:
//
//	mockgen -source=mappers/DtoMapper.go -destination=mocks/DtoMapperMock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "playbook/entities"
	requests "playbook/requests"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDtoMapperInterface is a mock of DtoMapperInterface interface.
type MockDtoMapperInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDtoMapperInterfaceMockRecorder
	isgomock struct{}
}

// MockDtoMapperInterfaceMockRecorder is the mock recorder for MockDtoMapperInterface.
type MockDtoMapperInterfaceMockRecorder struct {
	mock *MockDtoMapperInterface
}

// NewMockDtoMapperInterface creates a new mock instance.
func NewMockDtoMapperInterface(ctrl *gomock.Controller) *MockDtoMapperInterface {
	mock := &MockDtoMapperInterface{ctrl: ctrl}
	mock.recorder = &MockDtoMapperInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDtoMapperInterface) EXPECT() *MockDtoMapperInterfaceMockRecorder {
	return m.recorder
}

// GetPickupLineEntityFromDTO mocks base method.
func (m *MockDtoMapperInterface) GetPickupLineEntityFromDTO(pickupLineDTO *requests.PickupLineBodyRequest) *entities.PickupLine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPickupLineEntityFromDTO", pickupLineDTO)
	ret0, _ := ret[0].(*entities.PickupLine)
	return ret0
}

// GetPickupLineEntityFromDTO indicates an expected call of GetPickupLineEntityFromDTO.
func (mr *MockDtoMapperInterfaceMockRecorder) GetPickupLineEntityFromDTO(pickupLineDTO any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPickupLineEntityFromDTO", reflect.TypeOf((*MockDtoMapperInterface)(nil).GetPickupLineEntityFromDTO), pickupLineDTO)
}

// TagBodyRequestToEntity mocks base method.
func (m *MockDtoMapperInterface) TagBodyRequestToEntity(tagRequest *requests.TagBodyRequest, userUUID uuid.UUID) *entities.Tag {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagBodyRequestToEntity", tagRequest, userUUID)
	ret0, _ := ret[0].(*entities.Tag)
	return ret0
}

// TagBodyRequestToEntity indicates an expected call of TagBodyRequestToEntity.
func (mr *MockDtoMapperInterfaceMockRecorder) TagBodyRequestToEntity(tagRequest, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagBodyRequestToEntity", reflect.TypeOf((*MockDtoMapperInterface)(nil).TagBodyRequestToEntity), tagRequest, userUUID)
}

// UserCreateToEntity mocks base method.
func (m *MockDtoMapperInterface) UserCreateToEntity(arg0 *requests.CreateUserRequest) *entities.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserCreateToEntity", arg0)
	ret0, _ := ret[0].(*entities.User)
	return ret0
}

// UserCreateToEntity indicates an expected call of UserCreateToEntity.
func (mr *MockDtoMapperInterfaceMockRecorder) UserCreateToEntity(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserCreateToEntity", reflect.TypeOf((*MockDtoMapperInterface)(nil).UserCreateToEntity), arg0)
}
