// Code generated by MockGen. DO NOT EDIT.
// Source: services/ElasticSearchWrapper.go
//
// Generated by this command:
//
//	mockgen -source=services/ElasticSearchWrapper.go -destination=mocks/ElasticSearchWrapperMock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "playbook/entities"
	filters "playbook/filters"
	responses "playbook/responses"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockElasticSearchWrapperInterface is a mock of ElasticSearchWrapperInterface interface.
type MockElasticSearchWrapperInterface struct {
	ctrl     *gomock.Controller
	recorder *MockElasticSearchWrapperInterfaceMockRecorder
	isgomock struct{}
}

// MockElasticSearchWrapperInterfaceMockRecorder is the mock recorder for MockElasticSearchWrapperInterface.
type MockElasticSearchWrapperInterfaceMockRecorder struct {
	mock *MockElasticSearchWrapperInterface
}

// NewMockElasticSearchWrapperInterface creates a new mock instance.
func NewMockElasticSearchWrapperInterface(ctrl *gomock.Controller) *MockElasticSearchWrapperInterface {
	mock := &MockElasticSearchWrapperInterface{ctrl: ctrl}
	mock.recorder = &MockElasticSearchWrapperInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElasticSearchWrapperInterface) EXPECT() *MockElasticSearchWrapperInterfaceMockRecorder {
	return m.recorder
}

// CreatePickupLineIndex mocks base method.
func (m *MockElasticSearchWrapperInterface) CreatePickupLineIndex() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePickupLineIndex")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePickupLineIndex indicates an expected call of CreatePickupLineIndex.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) CreatePickupLineIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePickupLineIndex", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).CreatePickupLineIndex))
}

// CreateTagIndex mocks base method.
func (m *MockElasticSearchWrapperInterface) CreateTagIndex() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTagIndex")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTagIndex indicates an expected call of CreateTagIndex.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) CreateTagIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTagIndex", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).CreateTagIndex))
}

// CreateUserIndex mocks base method.
func (m *MockElasticSearchWrapperInterface) CreateUserIndex() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserIndex")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserIndex indicates an expected call of CreateUserIndex.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) CreateUserIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserIndex", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).CreateUserIndex))
}

// DeletePickupLine mocks base method.
func (m *MockElasticSearchWrapperInterface) DeletePickupLine(pickupLineUUID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePickupLine", pickupLineUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePickupLine indicates an expected call of DeletePickupLine.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) DeletePickupLine(pickupLineUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePickupLine", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).DeletePickupLine), pickupLineUUID)
}

// DeleteTag mocks base method.
func (m *MockElasticSearchWrapperInterface) DeleteTag(tag *entities.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTag", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTag indicates an expected call of DeleteTag.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) DeleteTag(tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTag", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).DeleteTag), tag)
}

// DeleteUser mocks base method.
func (m *MockElasticSearchWrapperInterface) DeleteUser(userUUID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", userUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) DeleteUser(userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).DeleteUser), userUUID)
}

// DeleteUserPickupLines mocks base method.
func (m *MockElasticSearchWrapperInterface) DeleteUserPickupLines(userUUID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserPickupLines", userUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserPickupLines indicates an expected call of DeleteUserPickupLines.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) DeleteUserPickupLines(userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserPickupLines", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).DeleteUserPickupLines), userUUID)
}

// ExistsIndex mocks base method.
func (m *MockElasticSearchWrapperInterface) ExistsIndex(indexName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsIndex", indexName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsIndex indicates an expected call of ExistsIndex.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) ExistsIndex(indexName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsIndex", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).ExistsIndex), indexName)
}

// GetPickupLineFeed mocks base method.
func (m *MockElasticSearchWrapperInterface) GetPickupLineFeed(userId uuid.UUID, arg1 *filters.PickupLineQueryFilters) (*responses.ElasticSearchPickupLineResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPickupLineFeed", userId, arg1)
	ret0, _ := ret[0].(*responses.ElasticSearchPickupLineResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPickupLineFeed indicates an expected call of GetPickupLineFeed.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) GetPickupLineFeed(userId, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPickupLineFeed", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).GetPickupLineFeed), userId, arg1)
}

// IndexPickupLine mocks base method.
func (m *MockElasticSearchWrapperInterface) IndexPickupLine(pickupLine *entities.PickupLine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexPickupLine", pickupLine)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexPickupLine indicates an expected call of IndexPickupLine.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) IndexPickupLine(pickupLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexPickupLine", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).IndexPickupLine), pickupLine)
}

// IndexTag mocks base method.
func (m *MockElasticSearchWrapperInterface) IndexTag(tag *entities.Tag) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTag", tag)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IndexTag indicates an expected call of IndexTag.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) IndexTag(tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTag", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).IndexTag), tag)
}

// IndexUser mocks base method.
func (m *MockElasticSearchWrapperInterface) IndexUser(user *entities.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexUser indicates an expected call of IndexUser.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) IndexUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexUser", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).IndexUser), user)
}

// SearchPickupLines mocks base method.
func (m *MockElasticSearchWrapperInterface) SearchPickupLines(userId uuid.UUID, arg1 *filters.PickupLineQueryFilters) (*responses.ElasticSearchPickupLineResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPickupLines", userId, arg1)
	ret0, _ := ret[0].(*responses.ElasticSearchPickupLineResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPickupLines indicates an expected call of SearchPickupLines.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) SearchPickupLines(userId, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPickupLines", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).SearchPickupLines), userId, arg1)
}

// SearchUsers mocks base method.
func (m *MockElasticSearchWrapperInterface) SearchUsers(arg0 *filters.UserQueryFilters) (*responses.ElasticSearchUserListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsers", arg0)
	ret0, _ := ret[0].(*responses.ElasticSearchUserListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsers indicates an expected call of SearchUsers.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) SearchUsers(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsers", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).SearchUsers), arg0)
}

// UpdatePickupLine mocks base method.
func (m *MockElasticSearchWrapperInterface) UpdatePickupLine(pickupLine *entities.PickupLine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePickupLine", pickupLine)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePickupLine indicates an expected call of UpdatePickupLine.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) UpdatePickupLine(pickupLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePickupLine", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).UpdatePickupLine), pickupLine)
}

// UpdateTag mocks base method.
func (m *MockElasticSearchWrapperInterface) UpdateTag(tag *entities.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTag", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTag indicates an expected call of UpdateTag.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) UpdateTag(tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTag", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).UpdateTag), tag)
}

// UpdateUserReaction mocks base method.
func (m *MockElasticSearchWrapperInterface) UpdateUserReaction(userId, pickupLineUUID uuid.UUID, newReaction, oldReaction *entities.Reaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserReaction", userId, pickupLineUUID, newReaction, oldReaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserReaction indicates an expected call of UpdateUserReaction.
func (mr *MockElasticSearchWrapperInterfaceMockRecorder) UpdateUserReaction(userId, pickupLineUUID, newReaction, oldReaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserReaction", reflect.TypeOf((*MockElasticSearchWrapperInterface)(nil).UpdateUserReaction), userId, pickupLineUUID, newReaction, oldReaction)
}
