// Code generated by MockGen. DO NOT EDIT.
// Source: services/ElasticSearchMapper.go
//
// Generated by this command:
//
//	mockgen -source=services/ElasticSearchMapper.go -destination=mocks/ElasticSearchMapperMock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	elastic_dtos "playbook/elastic_dtos"
	entities "playbook/entities"
	responses "playbook/responses"
	reflect "reflect"

	search "github.com/elastic/go-elasticsearch/v8/typedapi/core/search"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockElasticSearchMapperInterface is a mock of ElasticSearchMapperInterface interface.
type MockElasticSearchMapperInterface struct {
	ctrl     *gomock.Controller
	recorder *MockElasticSearchMapperInterfaceMockRecorder
	isgomock struct{}
}

// MockElasticSearchMapperInterfaceMockRecorder is the mock recorder for MockElasticSearchMapperInterface.
type MockElasticSearchMapperInterfaceMockRecorder struct {
	mock *MockElasticSearchMapperInterface
}

// NewMockElasticSearchMapperInterface creates a new mock instance.
func NewMockElasticSearchMapperInterface(ctrl *gomock.Controller) *MockElasticSearchMapperInterface {
	mock := &MockElasticSearchMapperInterface{ctrl: ctrl}
	mock.recorder = &MockElasticSearchMapperInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElasticSearchMapperInterface) EXPECT() *MockElasticSearchMapperInterfaceMockRecorder {
	return m.recorder
}

// elasticDtoToTags mocks base method.
func (m *MockElasticSearchMapperInterface) elasticDtoToTags(tagIds []uuid.UUID, userUUID uuid.UUID) ([]*entities.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "elasticDtoToTags", tagIds, userUUID)
	ret0, _ := ret[0].([]*entities.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// elasticDtoToTags indicates an expected call of elasticDtoToTags.
func (mr *MockElasticSearchMapperInterfaceMockRecorder) elasticDtoToTags(tagIds, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "elasticDtoToTags", reflect.TypeOf((*MockElasticSearchMapperInterface)(nil).elasticDtoToTags), tagIds, userUUID)
}

// getReaction mocks base method.
func (m *MockElasticSearchMapperInterface) getReaction(pickupLineId, userId uuid.UUID) (*entities.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getReaction", pickupLineId, userId)
	ret0, _ := ret[0].(*entities.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getReaction indicates an expected call of getReaction.
func (mr *MockElasticSearchMapperInterfaceMockRecorder) getReaction(pickupLineId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getReaction", reflect.TypeOf((*MockElasticSearchMapperInterface)(nil).getReaction), pickupLineId, userId)
}

// hydratePickupLineListFromElasticSearchResponse mocks base method.
func (m *MockElasticSearchMapperInterface) hydratePickupLineListFromElasticSearchResponse(response *search.Response, userId uuid.UUID) (*responses.ElasticSearchPickupLineResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "hydratePickupLineListFromElasticSearchResponse", response, userId)
	ret0, _ := ret[0].(*responses.ElasticSearchPickupLineResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// hydratePickupLineListFromElasticSearchResponse indicates an expected call of hydratePickupLineListFromElasticSearchResponse.
func (mr *MockElasticSearchMapperInterfaceMockRecorder) hydratePickupLineListFromElasticSearchResponse(response, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "hydratePickupLineListFromElasticSearchResponse", reflect.TypeOf((*MockElasticSearchMapperInterface)(nil).hydratePickupLineListFromElasticSearchResponse), response, userId)
}

// hydrateUserListFromElasticSearchResponse mocks base method.
func (m *MockElasticSearchMapperInterface) hydrateUserListFromElasticSearchResponse(response *search.Response) (*responses.ElasticSearchUserListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "hydrateUserListFromElasticSearchResponse", response)
	ret0, _ := ret[0].(*responses.ElasticSearchUserListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// hydrateUserListFromElasticSearchResponse indicates an expected call of hydrateUserListFromElasticSearchResponse.
func (mr *MockElasticSearchMapperInterfaceMockRecorder) hydrateUserListFromElasticSearchResponse(response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "hydrateUserListFromElasticSearchResponse", reflect.TypeOf((*MockElasticSearchMapperInterface)(nil).hydrateUserListFromElasticSearchResponse), response)
}

// pickupLineToElasticDTO mocks base method.
func (m *MockElasticSearchMapperInterface) pickupLineToElasticDTO(pickupLine *entities.PickupLine) *elastic_dtos.PickupLineElasticDTO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "pickupLineToElasticDTO", pickupLine)
	ret0, _ := ret[0].(*elastic_dtos.PickupLineElasticDTO)
	return ret0
}

// pickupLineToElasticDTO indicates an expected call of pickupLineToElasticDTO.
func (mr *MockElasticSearchMapperInterfaceMockRecorder) pickupLineToElasticDTO(pickupLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "pickupLineToElasticDTO", reflect.TypeOf((*MockElasticSearchMapperInterface)(nil).pickupLineToElasticDTO), pickupLine)
}

// pickupLineToUpdateElasticDTO mocks base method.
func (m *MockElasticSearchMapperInterface) pickupLineToUpdateElasticDTO(pickupLine *entities.PickupLine) *elastic_dtos.UpdatePickupLineElasticDTO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "pickupLineToUpdateElasticDTO", pickupLine)
	ret0, _ := ret[0].(*elastic_dtos.UpdatePickupLineElasticDTO)
	return ret0
}

// pickupLineToUpdateElasticDTO indicates an expected call of pickupLineToUpdateElasticDTO.
func (mr *MockElasticSearchMapperInterfaceMockRecorder) pickupLineToUpdateElasticDTO(pickupLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "pickupLineToUpdateElasticDTO", reflect.TypeOf((*MockElasticSearchMapperInterface)(nil).pickupLineToUpdateElasticDTO), pickupLine)
}

// tagToElasticDTO mocks base method.
func (m *MockElasticSearchMapperInterface) tagToElasticDTO(tag *entities.Tag) *elastic_dtos.TagElasticDTO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "tagToElasticDTO", tag)
	ret0, _ := ret[0].(*elastic_dtos.TagElasticDTO)
	return ret0
}

// tagToElasticDTO indicates an expected call of tagToElasticDTO.
func (mr *MockElasticSearchMapperInterfaceMockRecorder) tagToElasticDTO(tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "tagToElasticDTO", reflect.TypeOf((*MockElasticSearchMapperInterface)(nil).tagToElasticDTO), tag)
}

// userToElasticDTO mocks base method.
func (m *MockElasticSearchMapperInterface) userToElasticDTO(user *entities.User) *elastic_dtos.UserElasticDTO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "userToElasticDTO", user)
	ret0, _ := ret[0].(*elastic_dtos.UserElasticDTO)
	return ret0
}

// userToElasticDTO indicates an expected call of userToElasticDTO.
func (mr *MockElasticSearchMapperInterfaceMockRecorder) userToElasticDTO(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "userToElasticDTO", reflect.TypeOf((*MockElasticSearchMapperInterface)(nil).userToElasticDTO), user)
}
