// Code generated by MockGen. DO NOT EDIT.
// Source: services/ElasticSearchQueryWrapper.go
//
// Generated by this command:
//
//	mockgen -source=services/ElasticSearchQueryWrapper.go -destination=mocks/ElasticSearchQueryWrapperMock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	filters "playbook/filters"
	reflect "reflect"

	search "github.com/elastic/go-elasticsearch/v8/typedapi/core/search"
	types "github.com/elastic/go-elasticsearch/v8/typedapi/types"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQueryWrapperInterface is a mock of QueryWrapperInterface interface.
type MockQueryWrapperInterface struct {
	ctrl     *gomock.Controller
	recorder *MockQueryWrapperInterfaceMockRecorder
	isgomock struct{}
}

// MockQueryWrapperInterfaceMockRecorder is the mock recorder for MockQueryWrapperInterface.
type MockQueryWrapperInterfaceMockRecorder struct {
	mock *MockQueryWrapperInterface
}

// NewMockQueryWrapperInterface creates a new mock instance.
func NewMockQueryWrapperInterface(ctrl *gomock.Controller) *MockQueryWrapperInterface {
	mock := &MockQueryWrapperInterface{ctrl: ctrl}
	mock.recorder = &MockQueryWrapperInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryWrapperInterface) EXPECT() *MockQueryWrapperInterfaceMockRecorder {
	return m.recorder
}

// GetQuery mocks base method.
func (m *MockQueryWrapperInterface) GetQuery() *types.Query {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuery")
	ret0, _ := ret[0].(*types.Query)
	return ret0
}

// GetQuery indicates an expected call of GetQuery.
func (mr *MockQueryWrapperInterfaceMockRecorder) GetQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuery", reflect.TypeOf((*MockQueryWrapperInterface)(nil).GetQuery))
}

// SetMinimumShouldMatch mocks base method.
func (m *MockQueryWrapperInterface) SetMinimumShouldMatch(minimumShouldMatch int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMinimumShouldMatch", minimumShouldMatch)
}

// SetMinimumShouldMatch indicates an expected call of SetMinimumShouldMatch.
func (mr *MockQueryWrapperInterfaceMockRecorder) SetMinimumShouldMatch(minimumShouldMatch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMinimumShouldMatch", reflect.TypeOf((*MockQueryWrapperInterface)(nil).SetMinimumShouldMatch), minimumShouldMatch)
}

// WithContentSuggestion mocks base method.
func (m *MockQueryWrapperInterface) WithContentSuggestion(content string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithContentSuggestion", content)
}

// WithContentSuggestion indicates an expected call of WithContentSuggestion.
func (mr *MockQueryWrapperInterfaceMockRecorder) WithContentSuggestion(content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithContentSuggestion", reflect.TypeOf((*MockQueryWrapperInterface)(nil).WithContentSuggestion), content)
}

// WithDisplayNameSuggestionShould mocks base method.
func (m *MockQueryWrapperInterface) WithDisplayNameSuggestionShould(displayName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithDisplayNameSuggestionShould", displayName)
}

// WithDisplayNameSuggestionShould indicates an expected call of WithDisplayNameSuggestionShould.
func (mr *MockQueryWrapperInterfaceMockRecorder) WithDisplayNameSuggestionShould(displayName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithDisplayNameSuggestionShould", reflect.TypeOf((*MockQueryWrapperInterface)(nil).WithDisplayNameSuggestionShould), displayName)
}

// WithRandomScoring mocks base method.
func (m *MockQueryWrapperInterface) WithRandomScoring() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithRandomScoring")
}

// WithRandomScoring indicates an expected call of WithRandomScoring.
func (mr *MockQueryWrapperInterfaceMockRecorder) WithRandomScoring() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithRandomScoring", reflect.TypeOf((*MockQueryWrapperInterface)(nil).WithRandomScoring))
}

// WithStarredByUserFilter mocks base method.
func (m *MockQueryWrapperInterface) WithStarredByUserFilter(userUUID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithStarredByUserFilter", userUUID)
}

// WithStarredByUserFilter indicates an expected call of WithStarredByUserFilter.
func (mr *MockQueryWrapperInterfaceMockRecorder) WithStarredByUserFilter(userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStarredByUserFilter", reflect.TypeOf((*MockQueryWrapperInterface)(nil).WithStarredByUserFilter), userUUID)
}

// WithSuccessPercentageFilter mocks base method.
func (m *MockQueryWrapperInterface) WithSuccessPercentageFilter(successPercentage float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithSuccessPercentageFilter", successPercentage)
}

// WithSuccessPercentageFilter indicates an expected call of WithSuccessPercentageFilter.
func (mr *MockQueryWrapperInterfaceMockRecorder) WithSuccessPercentageFilter(successPercentage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithSuccessPercentageFilter", reflect.TypeOf((*MockQueryWrapperInterface)(nil).WithSuccessPercentageFilter), successPercentage)
}

// WithTagsShould mocks base method.
func (m *MockQueryWrapperInterface) WithTagsShould(tagIds []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithTagsShould", tagIds)
}

// WithTagsShould indicates an expected call of WithTagsShould.
func (mr *MockQueryWrapperInterfaceMockRecorder) WithTagsShould(tagIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTagsShould", reflect.TypeOf((*MockQueryWrapperInterface)(nil).WithTagsShould), tagIds)
}

// WithTimeScoring mocks base method.
func (m *MockQueryWrapperInterface) WithTimeScoring(scaleInDays int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithTimeScoring", scaleInDays)
}

// WithTimeScoring indicates an expected call of WithTimeScoring.
func (mr *MockQueryWrapperInterfaceMockRecorder) WithTimeScoring(scaleInDays any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTimeScoring", reflect.TypeOf((*MockQueryWrapperInterface)(nil).WithTimeScoring), scaleInDays)
}

// WithTitleSuggestionShould mocks base method.
func (m *MockQueryWrapperInterface) WithTitleSuggestionShould(title string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithTitleSuggestionShould", title)
}

// WithTitleSuggestionShould indicates an expected call of WithTitleSuggestionShould.
func (mr *MockQueryWrapperInterfaceMockRecorder) WithTitleSuggestionShould(title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTitleSuggestionShould", reflect.TypeOf((*MockQueryWrapperInterface)(nil).WithTitleSuggestionShould), title)
}

// WithUpvotedByUserFilter mocks base method.
func (m *MockQueryWrapperInterface) WithUpvotedByUserFilter(userUUID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithUpvotedByUserFilter", userUUID)
}

// WithUpvotedByUserFilter indicates an expected call of WithUpvotedByUserFilter.
func (mr *MockQueryWrapperInterfaceMockRecorder) WithUpvotedByUserFilter(userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithUpvotedByUserFilter", reflect.TypeOf((*MockQueryWrapperInterface)(nil).WithUpvotedByUserFilter), userUUID)
}

// WithUpvotesScoring mocks base method.
func (m *MockQueryWrapperInterface) WithUpvotesScoring(scoringWeight float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithUpvotesScoring", scoringWeight)
}

// WithUpvotesScoring indicates an expected call of WithUpvotesScoring.
func (mr *MockQueryWrapperInterfaceMockRecorder) WithUpvotesScoring(scoringWeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithUpvotesScoring", reflect.TypeOf((*MockQueryWrapperInterface)(nil).WithUpvotesScoring), scoringWeight)
}

// WithUserFilter mocks base method.
func (m *MockQueryWrapperInterface) WithUserFilter(userUUID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithUserFilter", userUUID)
}

// WithUserFilter indicates an expected call of WithUserFilter.
func (mr *MockQueryWrapperInterfaceMockRecorder) WithUserFilter(userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithUserFilter", reflect.TypeOf((*MockQueryWrapperInterface)(nil).WithUserFilter), userUUID)
}

// WithUsernameSuggestionShould mocks base method.
func (m *MockQueryWrapperInterface) WithUsernameSuggestionShould(username string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithUsernameSuggestionShould", username)
}

// WithUsernameSuggestionShould indicates an expected call of WithUsernameSuggestionShould.
func (mr *MockQueryWrapperInterfaceMockRecorder) WithUsernameSuggestionShould(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithUsernameSuggestionShould", reflect.TypeOf((*MockQueryWrapperInterface)(nil).WithUsernameSuggestionShould), username)
}

// WithVisibleFilter mocks base method.
func (m *MockQueryWrapperInterface) WithVisibleFilter(visible bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithVisibleFilter", visible)
}

// WithVisibleFilter indicates an expected call of WithVisibleFilter.
func (mr *MockQueryWrapperInterfaceMockRecorder) WithVisibleFilter(visible any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithVisibleFilter", reflect.TypeOf((*MockQueryWrapperInterface)(nil).WithVisibleFilter), visible)
}

// MockSearchRequestWrapperInterface is a mock of SearchRequestWrapperInterface interface.
type MockSearchRequestWrapperInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSearchRequestWrapperInterfaceMockRecorder
	isgomock struct{}
}

// MockSearchRequestWrapperInterfaceMockRecorder is the mock recorder for MockSearchRequestWrapperInterface.
type MockSearchRequestWrapperInterfaceMockRecorder struct {
	mock *MockSearchRequestWrapperInterface
}

// NewMockSearchRequestWrapperInterface creates a new mock instance.
func NewMockSearchRequestWrapperInterface(ctrl *gomock.Controller) *MockSearchRequestWrapperInterface {
	mock := &MockSearchRequestWrapperInterface{ctrl: ctrl}
	mock.recorder = &MockSearchRequestWrapperInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchRequestWrapperInterface) EXPECT() *MockSearchRequestWrapperInterfaceMockRecorder {
	return m.recorder
}

// applyFilters mocks base method.
func (m *MockSearchRequestWrapperInterface) applyFilters(arg0 *filters.PickupLineQueryFilters, requestingUser uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "applyFilters", arg0, requestingUser)
}

// applyFilters indicates an expected call of applyFilters.
func (mr *MockSearchRequestWrapperInterfaceMockRecorder) applyFilters(arg0, requestingUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "applyFilters", reflect.TypeOf((*MockSearchRequestWrapperInterface)(nil).applyFilters), arg0, requestingUser)
}

// applySorting mocks base method.
func (m *MockSearchRequestWrapperInterface) applySorting(pickupLineFilters *filters.PickupLineQueryFilters) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "applySorting", pickupLineFilters)
}

// applySorting indicates an expected call of applySorting.
func (mr *MockSearchRequestWrapperInterfaceMockRecorder) applySorting(pickupLineFilters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "applySorting", reflect.TypeOf((*MockSearchRequestWrapperInterface)(nil).applySorting), pickupLineFilters)
}

// applyUserFilters mocks base method.
func (m *MockSearchRequestWrapperInterface) applyUserFilters(arg0 *filters.UserQueryFilters) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "applyUserFilters", arg0)
}

// applyUserFilters indicates an expected call of applyUserFilters.
func (mr *MockSearchRequestWrapperInterfaceMockRecorder) applyUserFilters(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "applyUserFilters", reflect.TypeOf((*MockSearchRequestWrapperInterface)(nil).applyUserFilters), arg0)
}

// getRequest mocks base method.
func (m *MockSearchRequestWrapperInterface) getRequest() *search.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getRequest")
	ret0, _ := ret[0].(*search.Request)
	return ret0
}

// getRequest indicates an expected call of getRequest.
func (mr *MockSearchRequestWrapperInterfaceMockRecorder) getRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getRequest", reflect.TypeOf((*MockSearchRequestWrapperInterface)(nil).getRequest))
}

// withOffset mocks base method.
func (m *MockSearchRequestWrapperInterface) withOffset(offset int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "withOffset", offset)
}

// withOffset indicates an expected call of withOffset.
func (mr *MockSearchRequestWrapperInterfaceMockRecorder) withOffset(offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withOffset", reflect.TypeOf((*MockSearchRequestWrapperInterface)(nil).withOffset), offset)
}

// withSize mocks base method.
func (m *MockSearchRequestWrapperInterface) withSize(size int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "withSize", size)
}

// withSize indicates an expected call of withSize.
func (mr *MockSearchRequestWrapperInterfaceMockRecorder) withSize(size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withSize", reflect.TypeOf((*MockSearchRequestWrapperInterface)(nil).withSize), size)
}
