// Code generated by MockGen. DO NOT EDIT.
// Source: repositories/PickupLineRepository.go
//
// Generated by this command:
//
//	mockgen -source=repositories/PickupLineRepository.go -destination=mocks/PickupLineRepositoryMock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "playbook/entities"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPickupLineRepositoryInterface is a mock of PickupLineRepositoryInterface interface.
type MockPickupLineRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPickupLineRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockPickupLineRepositoryInterfaceMockRecorder is the mock recorder for MockPickupLineRepositoryInterface.
type MockPickupLineRepositoryInterfaceMockRecorder struct {
	mock *MockPickupLineRepositoryInterface
}

// NewMockPickupLineRepositoryInterface creates a new mock instance.
func NewMockPickupLineRepositoryInterface(ctrl *gomock.Controller) *MockPickupLineRepositoryInterface {
	mock := &MockPickupLineRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPickupLineRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPickupLineRepositoryInterface) EXPECT() *MockPickupLineRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPickupLineRepositoryInterface) Create(pickupLine *entities.PickupLine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", pickupLine)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPickupLineRepositoryInterfaceMockRecorder) Create(pickupLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPickupLineRepositoryInterface)(nil).Create), pickupLine)
}

// CreateReaction mocks base method.
func (m *MockPickupLineRepositoryInterface) CreateReaction(reaction *entities.Reaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReaction", reaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateReaction indicates an expected call of CreateReaction.
func (mr *MockPickupLineRepositoryInterfaceMockRecorder) CreateReaction(reaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReaction", reflect.TypeOf((*MockPickupLineRepositoryInterface)(nil).CreateReaction), reaction)
}

// Delete mocks base method.
func (m *MockPickupLineRepositoryInterface) Delete(pickupLine *entities.PickupLine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", pickupLine)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPickupLineRepositoryInterfaceMockRecorder) Delete(pickupLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPickupLineRepositoryInterface)(nil).Delete), pickupLine)
}

// DeleteReaction mocks base method.
func (m *MockPickupLineRepositoryInterface) DeleteReaction(reaction *entities.Reaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReaction", reaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReaction indicates an expected call of DeleteReaction.
func (mr *MockPickupLineRepositoryInterfaceMockRecorder) DeleteReaction(reaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReaction", reflect.TypeOf((*MockPickupLineRepositoryInterface)(nil).DeleteReaction), reaction)
}

// GetById mocks base method.
func (m *MockPickupLineRepositoryInterface) GetById(pickupLineUUID uuid.UUID) (*entities.PickupLine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", pickupLineUUID)
	ret0, _ := ret[0].(*entities.PickupLine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockPickupLineRepositoryInterfaceMockRecorder) GetById(pickupLineUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockPickupLineRepositoryInterface)(nil).GetById), pickupLineUUID)
}

// GetByIdAndUserId mocks base method.
func (m *MockPickupLineRepositoryInterface) GetByIdAndUserId(pickupLineUUID, userUUID uuid.UUID) (*entities.PickupLine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdAndUserId", pickupLineUUID, userUUID)
	ret0, _ := ret[0].(*entities.PickupLine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdAndUserId indicates an expected call of GetByIdAndUserId.
func (mr *MockPickupLineRepositoryInterfaceMockRecorder) GetByIdAndUserId(pickupLineUUID, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdAndUserId", reflect.TypeOf((*MockPickupLineRepositoryInterface)(nil).GetByIdAndUserId), pickupLineUUID, userUUID)
}

// GetPickupLineForVisibilityCheck mocks base method.
func (m *MockPickupLineRepositoryInterface) GetPickupLineForVisibilityCheck(pickupLineUUID uuid.UUID) (*entities.PickupLine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPickupLineForVisibilityCheck", pickupLineUUID)
	ret0, _ := ret[0].(*entities.PickupLine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPickupLineForVisibilityCheck indicates an expected call of GetPickupLineForVisibilityCheck.
func (mr *MockPickupLineRepositoryInterfaceMockRecorder) GetPickupLineForVisibilityCheck(pickupLineUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPickupLineForVisibilityCheck", reflect.TypeOf((*MockPickupLineRepositoryInterface)(nil).GetPickupLineForVisibilityCheck), pickupLineUUID)
}

// GetReactionByPickupLineIdAndUserId mocks base method.
func (m *MockPickupLineRepositoryInterface) GetReactionByPickupLineIdAndUserId(pickupLineUUID, userUUID uuid.UUID) (*entities.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReactionByPickupLineIdAndUserId", pickupLineUUID, userUUID)
	ret0, _ := ret[0].(*entities.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReactionByPickupLineIdAndUserId indicates an expected call of GetReactionByPickupLineIdAndUserId.
func (mr *MockPickupLineRepositoryInterfaceMockRecorder) GetReactionByPickupLineIdAndUserId(pickupLineUUID, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReactionByPickupLineIdAndUserId", reflect.TypeOf((*MockPickupLineRepositoryInterface)(nil).GetReactionByPickupLineIdAndUserId), pickupLineUUID, userUUID)
}

// GetStatisticsById mocks base method.
func (m *MockPickupLineRepositoryInterface) GetStatisticsById(pickupLineUUID uuid.UUID) (*entities.Statistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatisticsById", pickupLineUUID)
	ret0, _ := ret[0].(*entities.Statistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatisticsById indicates an expected call of GetStatisticsById.
func (mr *MockPickupLineRepositoryInterfaceMockRecorder) GetStatisticsById(pickupLineUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatisticsById", reflect.TypeOf((*MockPickupLineRepositoryInterface)(nil).GetStatisticsById), pickupLineUUID)
}

// Update mocks base method.
func (m *MockPickupLineRepositoryInterface) Update(pickupLine *entities.PickupLine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", pickupLine)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPickupLineRepositoryInterfaceMockRecorder) Update(pickupLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPickupLineRepositoryInterface)(nil).Update), pickupLine)
}

// UpdateReaction mocks base method.
func (m *MockPickupLineRepositoryInterface) UpdateReaction(reaction *entities.Reaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReaction", reaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReaction indicates an expected call of UpdateReaction.
func (mr *MockPickupLineRepositoryInterfaceMockRecorder) UpdateReaction(reaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReaction", reflect.TypeOf((*MockPickupLineRepositoryInterface)(nil).UpdateReaction), reaction)
}
