// Code generated by MockGen. DO NOT EDIT.
// Source: repositories/TagRepository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "playbook/entities"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTagRepositoryInterface is a mock of TagRepositoryInterface interface.
type MockTagRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryInterfaceMockRecorder
}

// MockTagRepositoryInterfaceMockRecorder is the mock recorder for MockTagRepositoryInterface.
type MockTagRepositoryInterfaceMockRecorder struct {
	mock *MockTagRepositoryInterface
}

// NewMockTagRepositoryInterface creates a new mock instance.
func NewMockTagRepositoryInterface(ctrl *gomock.Controller) *MockTagRepositoryInterface {
	mock := &MockTagRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepositoryInterface) EXPECT() *MockTagRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTagRepositoryInterface) Create(tag *entities.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTagRepositoryInterfaceMockRecorder) Create(tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTagRepositoryInterface)(nil).Create), tag)
}

// Delete mocks base method.
func (m *MockTagRepositoryInterface) Delete(tag *entities.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTagRepositoryInterfaceMockRecorder) Delete(tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTagRepositoryInterface)(nil).Delete), tag)
}

// GetById mocks base method.
func (m *MockTagRepositoryInterface) GetById(tagId string) (*entities.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", tagId)
	ret0, _ := ret[0].(*entities.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockTagRepositoryInterfaceMockRecorder) GetById(tagId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockTagRepositoryInterface)(nil).GetById), tagId)
}

// GetByUserId mocks base method.
func (m *MockTagRepositoryInterface) GetByUserId(userId uuid.UUID) ([]*entities.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserId", userId)
	ret0, _ := ret[0].([]*entities.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserId indicates an expected call of GetByUserId.
func (mr *MockTagRepositoryInterfaceMockRecorder) GetByUserId(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserId", reflect.TypeOf((*MockTagRepositoryInterface)(nil).GetByUserId), userId)
}

// GetListByTagIdAndUserIdList mocks base method.
func (m *MockTagRepositoryInterface) GetListByTagIdAndUserIdList(tagList [][]uuid.UUID) ([]*entities.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListByTagIdAndUserIdList", tagList)
	ret0, _ := ret[0].([]*entities.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListByTagIdAndUserIdList indicates an expected call of GetListByTagIdAndUserIdList.
func (mr *MockTagRepositoryInterfaceMockRecorder) GetListByTagIdAndUserIdList(tagList interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListByTagIdAndUserIdList", reflect.TypeOf((*MockTagRepositoryInterface)(nil).GetListByTagIdAndUserIdList), tagList)
}

// Update mocks base method.
func (m *MockTagRepositoryInterface) Update(tag *entities.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTagRepositoryInterfaceMockRecorder) Update(tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTagRepositoryInterface)(nil).Update), tag)
}
