// Code generated by MockGen. DO NOT EDIT.
// Source: services/TagService.go
//
// Generated by this command:
//
//	mockgen -source=services/TagService.go -destination=mocks/TagServiceMock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "playbook/entities"
	requests "playbook/requests"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTagServiceInterface is a mock of TagServiceInterface interface.
type MockTagServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTagServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockTagServiceInterfaceMockRecorder is the mock recorder for MockTagServiceInterface.
type MockTagServiceInterfaceMockRecorder struct {
	mock *MockTagServiceInterface
}

// NewMockTagServiceInterface creates a new mock instance.
func NewMockTagServiceInterface(ctrl *gomock.Controller) *MockTagServiceInterface {
	mock := &MockTagServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTagServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagServiceInterface) EXPECT() *MockTagServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTagServiceInterface) Create(tag *requests.TagBodyRequest, userUUID uuid.UUID) (*entities.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", tag, userUUID)
	ret0, _ := ret[0].(*entities.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTagServiceInterfaceMockRecorder) Create(tag, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTagServiceInterface)(nil).Create), tag, userUUID)
}

// Delete mocks base method.
func (m *MockTagServiceInterface) Delete(tag *entities.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTagServiceInterfaceMockRecorder) Delete(tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTagServiceInterface)(nil).Delete), tag)
}

// GetListByTagIdAndUserIdList mocks base method.
func (m *MockTagServiceInterface) GetListByTagIdAndUserIdList(tagList [][]uuid.UUID) ([]*entities.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListByTagIdAndUserIdList", tagList)
	ret0, _ := ret[0].([]*entities.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListByTagIdAndUserIdList indicates an expected call of GetListByTagIdAndUserIdList.
func (mr *MockTagServiceInterfaceMockRecorder) GetListByTagIdAndUserIdList(tagList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListByTagIdAndUserIdList", reflect.TypeOf((*MockTagServiceInterface)(nil).GetListByTagIdAndUserIdList), tagList)
}

// GetListByUserId mocks base method.
func (m *MockTagServiceInterface) GetListByUserId(userId uuid.UUID) ([]*entities.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListByUserId", userId)
	ret0, _ := ret[0].([]*entities.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListByUserId indicates an expected call of GetListByUserId.
func (mr *MockTagServiceInterfaceMockRecorder) GetListByUserId(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListByUserId", reflect.TypeOf((*MockTagServiceInterface)(nil).GetListByUserId), userId)
}

// Update mocks base method.
func (m *MockTagServiceInterface) Update(tagId string, tag *requests.TagBodyRequest) (*entities.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tagId, tag)
	ret0, _ := ret[0].(*entities.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTagServiceInterfaceMockRecorder) Update(tagId, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTagServiceInterface)(nil).Update), tagId, tag)
}
